name: Bandit
on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: jpetrucciani/bandit-check@master
      with:
        path: '.'

