name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2       
      - name: install black
        run: |
          pip install black==21.5b1
          pip install black==22.8.0
      - name: run black
        run: |
          black . --check --line-length 300
